VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
"GBHE6BHHQXQSNPGR52Q4656AQW2GYIXTXW3U3GBMIWHWOAFQQJJSDHKH",
"GALLAAUECD4AEA32WXQK3DYGZKYEQTMXEURLRBFDHSYWASI4FRJGW5EU"
]

[DOCUMENTATION]
ORG_NAME="DutchMedicineDog"
ORG_URL="https://DutchMedicineDog.com/"
ORG_LOGO="
ORG_DESCRIPTION="
ORG_KEYBASE="
ORG_TWITTER="https://twitter.com/DutchMedDog"
ORG_OFFICIAL_EMAIL="dutchmedicinedog@gmail.com"

[[CURRENCIES]]
code="DMDT"
issuer="GBHE6BHHQXQSNPGR52Q4656AQW2GYIXTXW3U3GBMIWHWOAFQQJJSDHKH"
display_decimals=7
fixed_number=00000000
is_asset_anchored=false
name="DutchMedicineDogToken"
desc="Duch Dog NFT artist"
conditions="10.000.000 supply. acount will be locked if everything is setup and done!"
image=" "

# DutchMedicineDogToken was issued using the open and inclusive Stellar blockchain network.
# Home Domain: DutchMedicineDog.com
# DutchMedicineDogToken
